export const ERROR_MESSAGES = {
  full_room: "The room is full. Please try again later",
  room_not_found: "The room does not exist",
};

export const IMAGE_NAMES = [
  "bee",
  "bird_house",
  "bird",
  "butterfly",
  "cherry",
  "clouds_and_sun",
  "dragonfly",
  "easter_egg",
  "flower_pot",
  "forest",
  "garden",
  "ice_cream",
  "kite",
  "ladybug",
  "lemonade",
  "maple_leaf",
  "mushroom",
  "pamela_hat",
  "paperboat",
  "pineapple",
  "pinwheel",
  "rabbit",
  "rainbow",
  "raincoat",
  "snail",
  "spring_calendar",
  "strawberry",
  "thunder",
  "tulip",
];
